### ISSUE TITLE
Card in Magarena not yet enabled

### ISSUE THREAD

**Issue by ShawnieBoy** [firemind/ProjectFiremind-Issues#17]
Sakura-Tribe Scout is showing that it doesn't have a script. I know this card was added to Magarena in the 1.49 release in April.

Could be possible that there are others that have slipped through the net.

**Comment by firemind** [comment]
Thanks for reporting this. The code I used to match magarena cards with the database was unable to correctly identify it (and others) because of the - in its name. I now read the magarena .txt files and use the name from in there.

There were other cards that I did not yet have in my database and that weren't enabled because of that. To fix this I set up a sync with mtgdb.info to ensure all cards are present.

Now the only cards that do not get mapped to the DB are the alternative names of the flip cards from Kamigawa (e.g. Shidako, Broodmistress) which do not have entries in my database. This shouldn't be a problem since they can't be added to decks in the first place.

Everything else should be properly enabled now.
