### ISSUE TITLE
AIRM matches stuck

### ISSUE THREAD

**Issue by melvinzhang** [firemind/ProjectFiremind-Issues#31]
See https://www.firemind.ch/ai_rating_matches/123 and https://www.firemind.ch/ai_rating_matches/125

They have been stuck at 31% and 78% percent respectively.

**Comment by firemind** [comment]
They are not stuck. The are failed permanently.

The worker is somewhat robust against exceptions but some problems will kill it completely. If you look at the last unfinished duel for each AIRM you'll see what caused the crash:
- https://www.firemind.ch/duels/506717
- https://www.firemind.ch/duels/510071

The reason their status is "new" instead of "failed" is that the system restarts the job (on the server side) but there no longer is a worker to pick up the job.

There is currently no way to restart AIRMs that died because of such an error (because it is most likely permanent and would thus start an endless loop).

**Comment by melvinzhang** [comment]
Thanks for looking into it. The failure message is extremely helpful.
