### ISSUE TITLE
Mono-color Archetypes include other basic lands

### ISSUE THREAD

**Issue by ShawnieBoy** [firemind/ProjectFiremind-Issues#41]
For example [Mono Black Infect](https://www.firemind.ch/archetypes/1187) includes Mountains, Plains, Forest and Island. [Mono Black Warriors](https://www.firemind.ch/archetypes/1013) includes at least Plains and Mountains.

**Comment by firemind** [comment]
What you see on that page isn't data that I manually enter. It is an overview of all the cards contained in decks that have been classified as a select archetype.

As to why to classification algorithm messes up so badly: It's mostly due to lack of data for archetypes in Vintage and Legacy. Since Mono Black Infect isn't really an established archetype in those formats the sample size is currently two decks. The decks that get missclassified as belonging to that archetype seem to be mostly old Standard decks which have no sample size in that format whatsoever.

That being said, I appreciate specific feedback like this. It just isn't something I can easily fix.

**Comment by ShawnieBoy** [comment]
Ahh, I see, I thought it was the other way around - 'these cards are what classifies a deck as this archetype'.
