### ISSUE TITLE
unable to login

### ISSUE THREAD

**Issue by JerichoPumpkin** [firemind/ProjectFiremind-Issues#44]
when I try to login, I get redirected to the homepage but I'm still not logged.
Whit a wrong password, all is as it should be (I remain on the login page and get the message wrong user/pasword).
I tried to reset the password, but it didn't change anything

**Comment by firemind** [comment]
Thanks for the report.

Turns out the memcached (where I store login sessinos) didn't start after a server reboot a couple of days ago. It's fixed now.

For some reason the caching library I use just swallows errors by default so I never got notified about the problem. I changed that setting so if this happens again I should be notified immediately.
