### ISSUE TITLE
Clusters interface is messed up

### ISSUE THREAD

**Issue by pshem** [firemind/ProjectFiremind-Issues#46]
Clusters at first look like a very useful option, allowing you to let evolution do the final touches on your deck, but the interface they're behind is not in a great shape. Here are some of the issues I've ran into:

- [x] Firstly, only the Lands cluster is automatically created. It would be very useful if creatures and spells were created automatically too. Depending on the language the server runs, I'd be happy to help with that.

- [x] Secondly, the `Lands` cluster is always autoselected. Even when I'm trying to adjust the number of copies I'd like to see tested and definitely don't want to change the card's cluster, it gets set to `Lands` and I have to set it back to `creatures`

- [X] Thirdly, the interface for adding cards to clusters doesn't update with added cards until you close and repoen the pop-up, making it hard to see if you're added all the cards to the clusters you want them in.

- [x] Fourthly, it would be very handy to get statistics on the number of cards in a certain cluster, to see if you've not missed any cards. Both points 3 & 4 sound like Javascript problems and I'd be glad to help with them.

**Comment by firemind** [comment]
Thanks for the feedback.

The (terribly named) **Maybe Entries**-Feature you describe is actually just a secondary purpose of the clusters. Primarily they are meant to show you statistics on how likely you are to draw X cards from the cluster by turn Y (using hypergeometric distributions).

> Firstly, only the Lands cluster is automatically created. It would be very useful if creatures and spells were created automatically too. Depending on the language the server runs, I'd be happy to help with that.

Adding this would be trivial. I'm just not sure what purpose those clusters would serve. I don't think their draw probability is particularly interesting.

The option to generate deck variations based on those clusters probably shouldn't be used on large clusters like lands or creatures since even just one or two maybe entries will lead to a huge amount of possible deck variations. To get statistically significant data on them you will need way too many duels.

The way I use the clusters for variations is something like "Pump Spells", "Burn Spells", "Artifact Hate" or just "Finishers". Small card groups within the deck on which you might want to tweak the numbers.

Now that I think about it, there should probably also be a view that shows you how the match-up win rates change between the variations.  

> Secondly, the Lands cluster is always autoselected. Even when I'm trying to adjust the number of copies I'd like to see tested and definitely don't want to change the card's cluster, it gets set to Lands and I have to set it back to creatures

This sounds like a bug. I'll look into it.

> Thirdly, the interface for adding cards to clusters doesn't update with added cards until you close and repoen the pop-up, making it hard to see if you're added all the cards to the clusters you want them in.

Is this what you described in #45? It should be fixed now.

> Fourthly, it would be very handy to get statistics on the number of cards in a certain cluster, to see if you've not missed any cards. 

When you click on a clusters name in the sidebar you get the statistics I described earlier and also the number of cards in the cluster. I do agree that it would be a worthwhile improvement to have a total displayed on the assignment screen.

**Comment by pshem** [comment]
I can confirm the issue no. 3 is fixed now, albeit at the price of clusters being reset - only the lands cluster is populated.

For issue no. 4, I didn't realise the lists worked - they were incomprehensible for an empty cluster and I didn't double check them until now. The odds of drawing a card from a particular cluster are very useful indeed. I hope I am an exception and that most people look at those statistics already filled for lands, where they make perfect sense.

I was thinking about the number of cards in a cluster in the editing menu, but as the intended use-case are small groups, this might not be warranted. Though it could still be useful to see if you've included all 20 lands if you have 6 different special lands as some people

Your explaination on the intended purpose of clusters does make sense, but I wouldn't consider it obvious. Do you think auto creating clusters for X cost cards would make it more intuitive?

**Comment by firemind** [comment]
> I can confirm the issue no. 3 is fixed now, albeit at the price of clusters being reset - only the lands cluster is populated.

This wasn't caused by my fix (which was just rendering the response correctly after an API change). It is most likely because you changed the deck list. I do not currently copy over the clusters when that happens though I admit I probably should. I might go with something similar o the sideboarding feature where you have to confirm copying them over to give you the option to keep the auto-generated ones instead. 

> For issue no. 4, I didn't realise the lists worked - they were incomprehensible for an empty cluster and I didn't double check them until now. 

I'll add a message for empty clusters to make this clearer.

> Do you think auto creating clusters for X cost cards would make it more intuitive?

I like the idea. Would you agree that only clusters for CMCs actually present in the deck should be created? And that 0 CMC should only include non-lands?

**Comment by pshem** [comment]
I did tweak some cards in the deck - didn't realise that would reset clusters. Keeping clusters with their current contents after a deck list change would be very welcome indeed.

>>For issue no. 4, I didn't realise the lists worked - they were incomprehensible for an empty cluster and I didn't double check them until now.
>
>I'll add a message for empty clusters to make this clearer.

That would be very handy, thank you.

> > Do you think auto creating clusters for X cost cards would make it more intuitive?
>
> I like the idea. Would you agree that only clusters for CMCs actually present in the deck should be created? And that 0 CMC should only include non-lands?

That fits my thoughts, although I'm unfamiliar with the term CMC.

**Comment by pshem** [comment]
Wow, you've already implemented everything I mentioned! Good job!

One thing I've noticed about the 0, 1, 2 etc. cost card clusters that get automatically created: Their names look a bit confusing, becaus ethere isn't quite enough of space between the quantity of cards within the cluster and it's name. 
![selectionshot_2018-06-15_11 53 11](https://user-images.githubusercontent.com/26800787/41464556-b83d2840-7092-11e8-9f03-2e9c7c58ddc6.png)

I would humbly suggest increasing the spacing, or adding a - in the names that start with a number(as in 0-cost cards).

**Comment by firemind** [comment]
> Their names look a bit confusing, becaus ethere isn't quite enough of space between the quantity of cards within the cluster and it's name.

Good point. I tried just adding the dash but it wasn't quite enough to make it look nice so now I align the card count to the right.

**Comment by pshem** [comment]
It's perfect now, thank you very much!
